
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author school
 */
public class FinishedPage extends javax.swing.JFrame {

    
    ArrayList<finishedcode> finisheditems;
    String header[] = new String[]{"Name", "Material", "Color", "QTY", "Date Shipped"}; 
    DefaultTableModel dtm;
    int row,col;
    private int i;
    

    /**
     * Creates new form FinishedPage
     */
    public FinishedPage() {
        initComponents();
        finisheditems = new ArrayList<>();
        dtm = new DefaultTableModel(header, 0);
        jTable2.setModel(dtm);
        this.setLocationRelativeTo(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabfinname = new javax.swing.JLabel();
        jlabfinmaterial = new javax.swing.JLabel();
        jlabfincolor = new javax.swing.JLabel();
        jlabfinqty = new javax.swing.JLabel();
        jfinName = new javax.swing.JTextField();
        jfinMaterial = new javax.swing.JTextField();
        jfinColor = new javax.swing.JTextField();
        jfinQty = new javax.swing.JTextField();
        jlabfincolor1 = new javax.swing.JLabel();
        jfinDate = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        jButtonfinadd = new javax.swing.JButton();
        jButtonfindelete = new javax.swing.JButton();
        jButtonfinupdate = new javax.swing.JButton();
        jButtonfinsearch = new javax.swing.JButton();
        jButtonHomefin = new javax.swing.JButton();
        jButtonfinprint = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0), 2));

        jlabfinname.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabfinname.setText("Name");
        jlabfinname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabfinmaterial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabfinmaterial.setText("Shape");
        jlabfinmaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabfincolor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabfincolor.setText("Color");
        jlabfincolor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabfinqty.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabfinqty.setText("Carats");
        jlabfinqty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabfincolor1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabfincolor1.setText("Date Shipped");
        jlabfincolor1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlabfinmaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabfinname, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabfincolor, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabfinqty, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlabfincolor1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(jfinQty, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(jfinColor, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jfinMaterial, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jfinName, javax.swing.GroupLayout.Alignment.LEADING))
                    .addComponent(jfinDate, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(458, 458, 458))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabfinname)
                    .addComponent(jfinName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabfinmaterial)
                    .addComponent(jfinMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabfincolor)
                    .addComponent(jfinColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabfinqty)
                    .addComponent(jfinQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabfincolor1)
                    .addComponent(jfinDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 255, 0)));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Material", "Color", "QTY"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable2);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 255, 51), 2));

        jButtonfinadd.setBackground(new java.awt.Color(153, 153, 255));
        jButtonfinadd.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonfinadd.setText("ADD");
        jButtonfinadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfinaddActionPerformed(evt);
            }
        });

        jButtonfindelete.setBackground(new java.awt.Color(153, 153, 255));
        jButtonfindelete.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonfindelete.setText("DELETE");
        jButtonfindelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfindeleteActionPerformed(evt);
            }
        });

        jButtonfinupdate.setBackground(new java.awt.Color(153, 153, 255));
        jButtonfinupdate.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonfinupdate.setText("UPDATE");
        jButtonfinupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfinupdateActionPerformed(evt);
            }
        });

        jButtonfinsearch.setBackground(new java.awt.Color(153, 153, 255));
        jButtonfinsearch.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonfinsearch.setText("SEARCH");
        jButtonfinsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfinsearchActionPerformed(evt);
            }
        });

        jButtonHomefin.setBackground(new java.awt.Color(153, 153, 255));
        jButtonHomefin.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonHomefin.setText("BACK");
        jButtonHomefin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomefinActionPerformed(evt);
            }
        });

        jButtonfinprint.setBackground(new java.awt.Color(153, 153, 255));
        jButtonfinprint.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonfinprint.setText("PRINT");
        jButtonfinprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonfinprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButtonfinadd)
                    .addComponent(jButtonfinprint))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonfindelete)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonfinsearch))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonfinupdate)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonHomefin, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(17, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButtonfinprint)
                        .addComponent(jButtonfinupdate, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButtonHomefin, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonfinadd, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonfindelete, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonfinsearch, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 522, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonfinaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfinaddActionPerformed
        // TODO add your handling code here:
        String finname = jfinName.getText(); //retrieve name from finished section
        String finmaterial = jfinMaterial.getText(); //retrieve material from finished section
        String fincolor = jfinColor.getText(); //retrieve color from finished section
        String finQTY = jfinQty.getText(); //retrieve QTY from finished section
        String findate = jfinDate.getText(); //retrieve QTY from finished section
                
        finisheditems.add(new finishedcode(finname, finmaterial, fincolor, finQTY, findate)); // adding retrieved values to the table using for loop
        dtm.setRowCount(0);
        for (int i=0; i < finisheditems.size(); i++){
            Object[] objs = {finisheditems.get(i).finname,finisheditems.get(i).finmaterial,finisheditems.get(i).fincolor,finisheditems.get(i).finQTY,finisheditems.get(i).findate};
            dtm.addRow(objs); // enables the table to store the values
        }
        
        clearField(); // once add is pressed, the preset values dissaper allowing a new set of inputs.  
    }//GEN-LAST:event_jButtonfinaddActionPerformed

    private void jButtonfindeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfindeleteActionPerformed
        // TODO add your handling code here:
        int DialogButton = JOptionPane.YES_NO_OPTION;
        int DialogResult = JOptionPane.showConfirmDialog(this, "delete this data", "delete", DialogButton); // user confirms whether to delete the data
        if(DialogResult == 0) {
            dtm.removeRow(row); // following code deleted the selected unwanted row
            finisheditems.remove(row);
            dtm.setRowCount(0);
            for (int i=0; i < finisheditems.size(); i++){
            Object[] objs = {finisheditems.get(i).finname,finisheditems.get(i).finmaterial,finisheditems.get(i).fincolor,finisheditems.get(i).finQTY, finisheditems.get(i).findate};
            dtm.addRow(objs); // enables the table to store the values
            }
        }
        
    }//GEN-LAST:event_jButtonfindeleteActionPerformed

    private void jButtonfinupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfinupdateActionPerformed
        // TODO add your handling code here:
        String updatefinname = jfinName.getText(); // retrieves new name input
        String updatefinmaterial = jfinMaterial.getText(); // retrieves new material input
        String updatefincolor = jfinColor.getText(); // retrieves new color input
        String updatefinQTY = jfinQty.getText(); // retrieves new qty input
        String updatefindate = jfinDate.getText(); 
        finisheditems.get(row).finname = updatefinname; // the new variable called updatependname, which has the retrieved code, gets updated.
        finisheditems.get(row).finmaterial = updatefinmaterial; // corresponding to the different variable such as pendname, it swaps the new value
        finisheditems.get(row).fincolor = updatefincolor; // this works by setting the specific one to blank then swaps it
        finisheditems.get(row).finQTY = updatefinQTY;
        finisheditems.get(row).findate = updatefindate;
        dtm.setRowCount(0);
        for (int i=0; i < finisheditems.size(); i++){
            Object[] objs = {finisheditems.get(i).finname,finisheditems.get(i).finmaterial,finisheditems.get(i).fincolor,finisheditems.get(i).finQTY, finisheditems.get(i).findate};
            dtm.addRow(objs);
        }
    }//GEN-LAST:event_jButtonfinupdateActionPerformed

    private void jButtonfinsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfinsearchActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this, "Search Item Name");
        for(int i =0; i < finisheditems.size(); i++){
            if(finisheditems.get(i).finname.equalsIgnoreCase(input)){
                JOptionPane.showMessageDialog(jButtonfinsearch, "Found!!!!");
                jfinName.setText(finisheditems.get(i).finname);
                jfinMaterial.setText(finisheditems.get(i).finmaterial);
                jfinColor.setText(finisheditems.get(i).fincolor);
                jfinQty.setText(finisheditems.get(i).finQTY);
                jfinDate.setText(finisheditems.get(i).findate);
                String location = finisheditems.get(i).toString();
                for(int j = 0; j < (FinishedItemLocation.getItemCount());j++){
                    
                    if(FinishedItemLocation.getItemAt(i).equals(location)){
                        FinishedItemLocation.setSelectedIndex(i);
                        
                      
                    }
          
                }
            
            }
      
        }
            
    }//GEN-LAST:event_jButtonfinsearchActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        row = jTable2.getSelectedRow();
        col = jTable2.getSelectedColumnCount();
        jfinName.setText(dtm.getValueAt(row, 0).toString());
        jfinMaterial.setText(dtm.getValueAt(row, 1).toString());
        jfinColor.setText(dtm.getValueAt(row, 2).toString());
        jfinQty.setText(dtm.getValueAt(row, 3).toString());
        jfinDate.setText(dtm.getValueAt(row, 4).toString());
        String location = finisheditems.get(i).toString();
        for (int i = 0; i<(FinishedItemLocation.getItemCount());i++){
            if (FinishedItemLocation.getItemAt(i).equals(location)){
                FinishedItemLocation.setSelectedIndex(i);
                
            }
        }
        
        
        
    }//GEN-LAST:event_jTable2MouseClicked

    private void jButtonHomefinActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomefinActionPerformed
        // TODO add your handling code here:
        LoginPage logpage = new LoginPage();
        
        logpage.show();
        
        dispose();

    }//GEN-LAST:event_jButtonHomefinActionPerformed

    private void jButtonfinprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonfinprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Pending Messages");
        MessageFormat footer = new MessageFormat("page {0, number, integer}");
        
        try{
            jTable2.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e){
         
            JOptionPane.showMessageDialog(null, e);
            

        }

        
     
    }//GEN-LAST:event_jButtonfinprintActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinishedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinishedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinishedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinishedPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FinishedPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHomefin;
    private javax.swing.JButton jButtonfinadd;
    private javax.swing.JButton jButtonfindelete;
    private javax.swing.JButton jButtonfinprint;
    private javax.swing.JButton jButtonfinsearch;
    private javax.swing.JButton jButtonfinupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jfinColor;
    private javax.swing.JTextField jfinDate;
    private javax.swing.JTextField jfinMaterial;
    private javax.swing.JTextField jfinName;
    private javax.swing.JTextField jfinQty;
    private javax.swing.JLabel jlabfincolor;
    private javax.swing.JLabel jlabfincolor1;
    private javax.swing.JLabel jlabfinmaterial;
    private javax.swing.JLabel jlabfinname;
    private javax.swing.JLabel jlabfinqty;
    // End of variables declaration//GEN-END:variables

    private void clearField() {   // clears the fields in the different input section once the values are added
        jfinName.setText("");
        jfinMaterial.setText("");
        jfinColor.setText("");
        jfinQty.setText("");
        jfinDate.setText("");
   
    }
    
    private static class FinishedItemLocation{ //methods created for search algorithim

        private static int getItemCount() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static void setSelectedIndex(int i) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static Object getItemAt(int i) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public FinishedItemLocation() {
        }
        
        
    }
    
   
   
    
}
