
import java.text.MessageFormat;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import javax.swing.JTable;
/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author school
 */
public class PendingPage extends javax.swing.JFrame {
    
    ArrayList<pendingcode> pendingitems;
    String header[] = new String[]{"Name", "Material", "Color", "QTY"}; 
    DefaultTableModel dtm;
    int row,col;
    private int i;

    /**
     * Creates new form PendingPage
     */
    public PendingPage() {
        initComponents();
        pendingitems = new ArrayList<>();
        dtm = new DefaultTableModel(header, 0);
        jTable1.setModel(dtm);
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlabmaterial = new javax.swing.JLabel();
        jlabname = new javax.swing.JLabel();
        jlabcolor = new javax.swing.JLabel();
        jlabqty = new javax.swing.JLabel();
        jTextMaterial = new javax.swing.JTextField();
        jTextColor = new javax.swing.JTextField();
        jTextName = new javax.swing.JTextField();
        jTextQty = new javax.swing.JTextField();
        jTextQty1 = new javax.swing.JTextField();
        jlabqty1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButtonadd = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jButtonsearch = new javax.swing.JButton();
        jButtonHomepen = new javax.swing.JButton();
        jButtonprint = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 2));

        jlabmaterial.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabmaterial.setText("Shape");
        jlabmaterial.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabname.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabname.setText("Name");
        jlabname.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabcolor.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabcolor.setText("Color");
        jlabcolor.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabqty.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabqty.setText("Carats");
        jlabqty.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jlabqty1.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jlabqty1.setText("Expected  Date");
        jlabqty1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlabname, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jlabmaterial, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlabcolor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jlabqty, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(46, 46, 46)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextQty1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTextColor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jlabqty1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jTextQty, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(456, 456, 456))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabname)
                    .addComponent(jTextName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(20, 20, 20)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabmaterial)
                    .addComponent(jTextMaterial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabcolor)
                    .addComponent(jTextColor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabqty)
                    .addComponent(jTextQty1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlabqty1)
                    .addComponent(jTextQty, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        jPanel2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(255, 0, 0), 2, true));

        jButtonadd.setBackground(new java.awt.Color(153, 153, 255));
        jButtonadd.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonadd.setForeground(new java.awt.Color(0, 0, 51));
        jButtonadd.setText("ADD");
        jButtonadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonaddActionPerformed(evt);
            }
        });

        jButtonupdate.setBackground(new java.awt.Color(153, 153, 255));
        jButtonupdate.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonupdate.setForeground(new java.awt.Color(0, 0, 51));
        jButtonupdate.setText("UPDATE");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });

        jButtondelete.setBackground(new java.awt.Color(153, 153, 255));
        jButtondelete.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtondelete.setForeground(new java.awt.Color(0, 0, 51));
        jButtondelete.setText("DELETE");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jButtonsearch.setBackground(new java.awt.Color(153, 153, 255));
        jButtonsearch.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonsearch.setForeground(new java.awt.Color(0, 0, 51));
        jButtonsearch.setText("SEARCH");
        jButtonsearch.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonsearchActionPerformed(evt);
            }
        });

        jButtonHomepen.setBackground(new java.awt.Color(153, 153, 255));
        jButtonHomepen.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonHomepen.setForeground(new java.awt.Color(0, 0, 51));
        jButtonHomepen.setText("BACK");
        jButtonHomepen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonHomepenActionPerformed(evt);
            }
        });

        jButtonprint.setBackground(new java.awt.Color(153, 153, 255));
        jButtonprint.setFont(new java.awt.Font("Georgia", 0, 14)); // NOI18N
        jButtonprint.setForeground(new java.awt.Color(0, 0, 51));
        jButtonprint.setText("PRINT");
        jButtonprint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonprintActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonadd)
                        .addGap(38, 38, 38)
                        .addComponent(jButtondelete))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButtonsearch)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonprint, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButtonHomepen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonupdate, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE))
                .addContainerGap(55, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonadd)
                    .addComponent(jButtonupdate)
                    .addComponent(jButtondelete))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonprint)
                    .addComponent(jButtonsearch)
                    .addComponent(jButtonHomepen, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTable1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 51)));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Material", "Color", "QTY"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Integer.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable1.setGridColor(new java.awt.Color(0, 0, 0));
        jTable1.setInheritsPopupMenu(true);
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(3).setResizable(false);
        }

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 448, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonaddActionPerformed
        // TODO add your handling code here:
        String pendname = jTextName.getText(); //retrieve name from pending section
        String pendmaterial = jTextMaterial.getText(); //retrieve material from pending section
        String pendcolor = jTextColor.getText(); //retrieve color from pending section
        String pendQTY = jTextQty.getText(); //retrieve QTY from pending section
        
        pendingitems.add(new pendingcode(pendname, pendmaterial, pendcolor, pendQTY)); // adding retrieved values to the table using for loop
        dtm.setRowCount(0);
        for (int i=0; i < pendingitems.size(); i++){
            Object[] objs = {pendingitems.get(i).pendname,pendingitems.get(i).pendmaterial,pendingitems.get(i).pendcolor,pendingitems.get(i).pendQTY};
            dtm.addRow(objs); // enables the table to store the values
        }
        
        clearField(); // once add is pressed, the preset values dissaper allowing a new set of inputs. 
    }//GEN-LAST:event_jButtonaddActionPerformed

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        // TODO add your handling code here:
        int DialogButton = JOptionPane.YES_NO_OPTION;
        int DialogResult = JOptionPane.showConfirmDialog(this, "delete this data", "delete", DialogButton); // user confirms whether to delete the data
        if(DialogResult == 0) {
            dtm.removeRow(row); // following code deleted the selected unwanted row
            pendingitems.remove(row);
            dtm.setRowCount(0);
            for (int i=0; i < pendingitems.size(); i++){
            Object[] objs = {pendingitems.get(i).pendname,pendingitems.get(i).pendmaterial,pendingitems.get(i).pendcolor,pendingitems.get(i).pendQTY};
            dtm.addRow(objs); // enables the table to store the values
            }
        }
        
    }//GEN-LAST:event_jButtondeleteActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        // TODO add your handling code here:
        String updatependname = jTextName.getText(); // retrieves new name input
        String updatependmaterial = jTextMaterial.getText(); // retrieves new material input
        String updatependcolor = jTextColor.getText(); // retrieves new color input
        String updatependQTY = jTextQty.getText(); // retrieves new qty input
        pendingitems.get(row).pendname = updatependname; // the new variable called updatependname, which has the retrieved code, gets updated.
        pendingitems.get(row).pendmaterial = updatependmaterial; // corresponding to the different variable such as pendname, it swaps the new value
        pendingitems.get(row).pendcolor = updatependcolor; // this works by setting the specific one to blank then swaps it
        pendingitems.get(row).pendQTY = updatependQTY;
        dtm.setRowCount(0);
        for (int i=0; i < pendingitems.size(); i++){
            Object[] objs = {pendingitems.get(i).pendname,pendingitems.get(i).pendmaterial,pendingitems.get(i).pendcolor,pendingitems.get(i).pendQTY};
            dtm.addRow(objs);
        }
        
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jButtonsearchActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonsearchActionPerformed
        // TODO add your handling code here:
        String input = JOptionPane.showInputDialog(this,"Search Item Name:");
        for (int i = 0; i < pendingitems.size(); i++){
            if (pendingitems.get(i).pendname.equalsIgnoreCase(input)){
                JOptionPane.showMessageDialog(jButtonsearch, "Found!!!", "Search ", 2);
                jTextName.setText(pendingitems.get(i).pendname);
                jTextMaterial.setText(pendingitems.get(i).pendmaterial);
                jTextColor.setText(pendingitems.get(i).pendcolor);
                jTextQty.setText(pendingitems.get(i).pendQTY);
                String location = pendingitems.get(i).toString();
                for (int j = 0; j<(PendingitemLocation.getItemCount());j++){
                 if(PendingitemLocation.getItemAt(i).equals(location)){
                     PendingitemLocation.setSelectedIndex(i);
                          
                }
                 
                }
            }
        }
    }//GEN-LAST:event_jButtonsearchActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
        row = jTable1.getSelectedRow();
        col = jTable1.getSelectedColumnCount();
        jTextName.setText(dtm.getValueAt(row, 0).toString());
        jTextMaterial.setText(dtm.getValueAt(row, 1).toString());
        jTextColor.setText(dtm.getValueAt(row, 2).toString());
        jTextQty.setText(dtm.getValueAt(row, 3).toString());
        String location = pendingitems.get(i).toString();
        for (int i = 0; i<(PendingitemLocation.getItemCount());i++){
            if (PendingitemLocation.getItemAt(i).equals(location)){
                PendingitemLocation.setSelectedIndex(i);
                
            }
        }
        
    }//GEN-LAST:event_jTable1MouseClicked

    private void jButtonHomepenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonHomepenActionPerformed
        // TODO add your handling code here:
        
        LoginPage logpage = new LoginPage();
        
        logpage.show();
        
        dispose();

        
    }//GEN-LAST:event_jButtonHomepenActionPerformed

    private void jButtonprintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonprintActionPerformed
        // TODO add your handling code here:
        MessageFormat header = new MessageFormat("Pending Messages");
        MessageFormat footer = new MessageFormat("page {0, number, integer}");
        
        try{
            jTable1.print(JTable.PrintMode.NORMAL, header, footer);
        } catch (java.awt.print.PrinterException e){
         
            JOptionPane.showMessageDialog(null, e);
            

        }

    }//GEN-LAST:event_jButtonprintActionPerformed

    
        
    private void clearField() {
        jTextName.setText("");
        jTextMaterial.setText("");
        jTextColor.setText("");
        jTextQty.setText("");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PendingPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PendingPage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonHomepen;
    private javax.swing.JButton jButtonadd;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonprint;
    private javax.swing.JButton jButtonsearch;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextColor;
    private javax.swing.JTextField jTextMaterial;
    private javax.swing.JTextField jTextName;
    private javax.swing.JTextField jTextQty;
    private javax.swing.JTextField jTextQty1;
    private javax.swing.JLabel jlabcolor;
    private javax.swing.JLabel jlabmaterial;
    private javax.swing.JLabel jlabname;
    private javax.swing.JLabel jlabqty;
    private javax.swing.JLabel jlabqty1;
    // End of variables declaration//GEN-END:variables

    private static class PendingitemLocation { //methods created for search algorithim

        private static int getItemCount() {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static void setSelectedIndex(int i) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        private static Object getItemAt(int i) {
            throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

        public PendingitemLocation() {
        }
        
        
    }
}
